function CodeDefine() { 
this.def = new Array();
this.def["FOC_iPhaseAMeas_S"] = {file: "FOC_Controller_c.html",line:23,type:"var"};
this.def["FOC_iPhaseBMeas_S"] = {file: "FOC_Controller_c.html",line:24,type:"var"};
this.def["FOC_nSpeedMeasRaw_S"] = {file: "FOC_Controller_c.html",line:25,type:"var"};
this.def["FOC_cntThetaElec_S"] = {file: "FOC_Controller_c.html",line:26,type:"var"};
this.def["FOC_iPhaseCMeas_S"] = {file: "FOC_Controller_c.html",line:27,type:"var"};
this.def["Position_degMeasured_S"] = {file: "FOC_Controller_c.html",line:28,type:"var"};
this.def["Motor_iTorque_S"] = {file: "FOC_Controller_c.html",line:29,type:"var"};
this.def["Speed_nSetPoint_S"] = {file: "FOC_Controller_c.html",line:30,type:"var"};
this.def["Speed_nMeas_S"] = {file: "FOC_Controller_c.html",line:31,type:"var"};
this.def["FOC_iIqSP_S"] = {file: "FOC_Controller_c.html",line:32,type:"var"};
this.def["FOC_iIdSP_S"] = {file: "FOC_Controller_c.html",line:33,type:"var"};
this.def["FOC_thetaElecMeas_S"] = {file: "FOC_Controller_c.html",line:34,type:"var"};
this.def["FOC_sinCoefficient_S"] = {file: "FOC_Controller_c.html",line:35,type:"var"};
this.def["FOC_cosCoefficient_S"] = {file: "FOC_Controller_c.html",line:36,type:"var"};
this.def["FOC_iIdMeas_S"] = {file: "FOC_Controller_c.html",line:37,type:"var"};
this.def["FOC_iIqMeas_S"] = {file: "FOC_Controller_c.html",line:38,type:"var"};
this.def["FOC_uVqSP_S"] = {file: "FOC_Controller_c.html",line:39,type:"var"};
this.def["FOC_uVdSP_S"] = {file: "FOC_Controller_c.html",line:40,type:"var"};
this.def["FOC_uPhaseUVolt_S"] = {file: "FOC_Controller_c.html",line:41,type:"var"};
this.def["FOC_uPhaseVVolt_S"] = {file: "FOC_Controller_c.html",line:42,type:"var"};
this.def["FOC_uPhaseWVolt_S"] = {file: "FOC_Controller_c.html",line:43,type:"var"};
this.def["SVM_uPhaseU_S"] = {file: "FOC_Controller_c.html",line:44,type:"var"};
this.def["SVM_uPhaseV_S"] = {file: "FOC_Controller_c.html",line:45,type:"var"};
this.def["SVM_uPhaseW_S"] = {file: "FOC_Controller_c.html",line:46,type:"var"};
this.def["FOC_bInitPID_S"] = {file: "FOC_Controller_c.html",line:47,type:"var"};
this.def["Motor_flagFindPos_S"] = {file: "FOC_Controller_c.html",line:48,type:"var"};
this.def["FOC_cntThetaElecOffset_S"] = {file: "FOC_Controller_c.html",line:51,type:"var"};
this.def["FOC_bManualVdVq_C"] = {file: "FOC_Controller_c.html",line:57,type:"var"};
this.def["FOC_iIdSP_C"] = {file: "FOC_Controller_c.html",line:58,type:"var"};
this.def["FOC_kiPID_C"] = {file: "FOC_Controller_c.html",line:59,type:"var"};
this.def["FOC_kpPID_C"] = {file: "FOC_Controller_c.html",line:60,type:"var"};
this.def["FOC_uBusVoltage_C"] = {file: "FOC_Controller_c.html",line:61,type:"var"};
this.def["FOC_uFindPosVd_C"] = {file: "FOC_Controller_c.html",line:63,type:"var"};
this.def["FOC_uManualVd_C"] = {file: "FOC_Controller_c.html",line:64,type:"var"};
this.def["FOC_uManualVq_C"] = {file: "FOC_Controller_c.html",line:65,type:"var"};
this.def["Motor_bFindPosEnable_C"] = {file: "FOC_Controller_c.html",line:66,type:"var"};
this.def["Motor_facTrq2Current_C"] = {file: "FOC_Controller_c.html",line:67,type:"var"};
this.def["Motor_swtMode_C"] = {file: "FOC_Controller_c.html",line:68,type:"var"};
this.def["Motor_tiFindPos_C"] = {file: "FOC_Controller_c.html",line:75,type:"var"};
this.def["Motor_trqTorqueSetPoint_C"] = {file: "FOC_Controller_c.html",line:76,type:"var"};
this.def["Position_degSetPoint_C"] = {file: "FOC_Controller_c.html",line:77,type:"var"};
this.def["Position_kiPID_C"] = {file: "FOC_Controller_c.html",line:78,type:"var"};
this.def["Position_kpPID_C"] = {file: "FOC_Controller_c.html",line:79,type:"var"};
this.def["Position_nPIDMax_C"] = {file: "FOC_Controller_c.html",line:80,type:"var"};
this.def["Speed_iPIDMax_C"] = {file: "FOC_Controller_c.html",line:82,type:"var"};
this.def["Speed_kiPID_C"] = {file: "FOC_Controller_c.html",line:84,type:"var"};
this.def["Speed_kpPID_C"] = {file: "FOC_Controller_c.html",line:85,type:"var"};
this.def["Speed_nSetPoint_C"] = {file: "FOC_Controller_c.html",line:86,type:"var"};
this.def["Speed_tiFilter_C"] = {file: "FOC_Controller_c.html",line:87,type:"var"};
this.def["FOC_Controller_B"] = {file: "FOC_Controller_c.html",line:90,type:"var"};
this.def["FOC_Controller_DW"] = {file: "FOC_Controller_c.html",line:93,type:"var"};
this.def["FOC_Controller.c:FOC_Controller_M_"] = {file: "FOC_Controller_c.html",line:96,type:"var"};
this.def["FOC_Controller_M"] = {file: "FOC_Controller_c.html",line:97,type:"var"};
this.def["FOC_Controller.c:rate_scheduler"] = {file: "FOC_Controller_c.html",line:105,type:"fcn"};
this.def["FOC_Controller_step"] = {file: "FOC_Controller_c.html",line:123,type:"fcn"};
this.def["FOC_Controller_initialize"] = {file: "FOC_Controller_c.html",line:152,type:"fcn"};
this.def["FOC_Controller_terminate"] = {file: "FOC_Controller_c.html",line:212,type:"fcn"};
this.def["B_FOC_Controller_T"] = {file: "FOC_Controller_h.html",line:50,type:"type"};
this.def["DW_FOC_Controller_T"] = {file: "FOC_Controller_h.html",line:71,type:"type"};
this.def["RT_MODEL_FOC_Controller_T"] = {file: "FOC_Controller_types_h.html",line:25,type:"type"};
this.def["CurrentControl_Co"] = {file: "CurrentControl_c.html",line:26,type:"fcn"};
this.def["lib_filter"] = {file: "CurrentControl_c.html",line:422,type:"fcn"};
this.def["B_lib_filter_T"] = {file: "CurrentControl_h.html",line:32,type:"type"};
this.def["ModeRegul_Co_Init"] = {file: "ModeRegul_c.html",line:32,type:"fcn"};
this.def["ModeRegul_Co"] = {file: "ModeRegul_c.html",line:44,type:"fcn"};
this.def["PositionControl_Co"] = {file: "PositionControl_c.html",line:26,type:"fcn"};
this.def["SpeedControl_Co_Init"] = {file: "SpeedControl_c.html",line:26,type:"fcn"};
this.def["SpeedControl_Co_Disable"] = {file: "SpeedControl_c.html",line:35,type:"fcn"};
this.def["SpeedControl_Co"] = {file: "SpeedControl_c.html",line:41,type:"fcn"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:50,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:81,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:86,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:91,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:98,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:105,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:112,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:119,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:126,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:133,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:151,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["FOC_Controller_c.html"] = "../FOC_Controller.c";
	this.html2Root["FOC_Controller_c.html"] = "FOC_Controller_c.html";
	this.html2SrcPath["FOC_Controller_h.html"] = "../FOC_Controller.h";
	this.html2Root["FOC_Controller_h.html"] = "FOC_Controller_h.html";
	this.html2SrcPath["FOC_Controller_private_h.html"] = "../FOC_Controller_private.h";
	this.html2Root["FOC_Controller_private_h.html"] = "FOC_Controller_private_h.html";
	this.html2SrcPath["FOC_Controller_types_h.html"] = "../FOC_Controller_types.h";
	this.html2Root["FOC_Controller_types_h.html"] = "FOC_Controller_types_h.html";
	this.html2SrcPath["CurrentControl_c.html"] = "../CurrentControl.c";
	this.html2Root["CurrentControl_c.html"] = "CurrentControl_c.html";
	this.html2SrcPath["CurrentControl_h.html"] = "../CurrentControl.h";
	this.html2Root["CurrentControl_h.html"] = "CurrentControl_h.html";
	this.html2SrcPath["ModeRegul_c.html"] = "../ModeRegul.c";
	this.html2Root["ModeRegul_c.html"] = "ModeRegul_c.html";
	this.html2SrcPath["ModeRegul_h.html"] = "../ModeRegul.h";
	this.html2Root["ModeRegul_h.html"] = "ModeRegul_h.html";
	this.html2SrcPath["PositionControl_c.html"] = "../PositionControl.c";
	this.html2Root["PositionControl_c.html"] = "PositionControl_c.html";
	this.html2SrcPath["PositionControl_h.html"] = "../PositionControl.h";
	this.html2Root["PositionControl_h.html"] = "PositionControl_h.html";
	this.html2SrcPath["SpeedControl_c.html"] = "../SpeedControl.c";
	this.html2Root["SpeedControl_c.html"] = "SpeedControl_c.html";
	this.html2SrcPath["SpeedControl_h.html"] = "../SpeedControl.h";
	this.html2Root["SpeedControl_h.html"] = "SpeedControl_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"FOC_Controller_c.html","FOC_Controller_h.html","FOC_Controller_private_h.html","FOC_Controller_types_h.html","CurrentControl_c.html","CurrentControl_h.html","ModeRegul_c.html","ModeRegul_h.html","PositionControl_c.html","PositionControl_h.html","SpeedControl_c.html","SpeedControl_h.html","rtwtypes_h.html","rtmodel_h.html"];
