function build_smo_hfi_model()
%BUILD_SMO_HFI_MODEL  Create SMO_HFI_FOC.slx from scratch.
% The MATLAB Function blocks are filled from the sibling mf_*.m files, so
% the algorithms can be edited either in the model or in the text files.
here = fileparts(mfilename('fullpath'));
old  = cd(here);
cleanup = onCleanup(@() cd(old));
mdl  = 'SMO_HFI_FOC';
p    = pmsm_params();

if bdIsLoaded(mdl)
    set_param(mdl, 'Dirty', 'off');
    close_system(mdl, 0);
end
if exist([here filesep mdl '.slx'], 'file')
    delete([here filesep mdl '.slx']);
end

new_system(mdl);

cfgstr = sprintf(['[%.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g %.10g]'], ...
    p.R, p.Ld, p.Lq, p.psi, p.pp, p.J, p.F, p.Ts, p.Udc, p.fh, p.Vh, p.wlo, p.whi);

add_block('simulink/Sources/Clock',    [mdl '/Clock'], 'Position', [30 520 60 550]);
add_block('simulink/Sources/Constant', [mdl '/CFG'], 'Value', cfgstr, 'Position', [15 560 75 590]);

add_chart(mdl, 'Ref_Profile',     fullfile(here,'mf_Ref_Profile.m'),     [110 480 215 560]);
add_chart(mdl, 'FOC_Controller',  fullfile(here,'mf_FOC_Controller.m'),  [280 440 400 600]);
add_chart(mdl, 'HFI_Observer',    fullfile(here,'mf_HFI_Observer.m'),    [450 440 570 600]);
add_chart(mdl, 'PMSM_Plant',      fullfile(here,'mf_PMSM_Plant.m'),      [710 430 830 610]);
add_chart(mdl, 'SMO_PLL',         fullfile(here,'mf_SMO_PLL.m'),         [880 430 1000 600]);
add_chart(mdl, 'Observer_Fusion', fullfile(here,'mf_Observer_Fusion.m'), [1050 440 1170 570]);

add_block('simulink/Discrete/Unit Delay', [mdl '/Delay_ua'], ...
    'SampleTime', num2str(p.Ts), 'InitialCondition', '0', 'Position', [610 480 645 510]);
add_block('simulink/Discrete/Unit Delay', [mdl '/Delay_ub'], ...
    'SampleTime', num2str(p.Ts), 'InitialCondition', '0', 'Position', [610 530 645 560]);
% One sample old angle and speed for the current loops: matches the real
% computation delay and breaks the controller - HFI - fusion algebraic loop.
add_block('simulink/Discrete/Unit Delay', [mdl '/Delay_theta'], ...
    'SampleTime', num2str(p.Ts), 'InitialCondition', '0', 'Position', [1190 440 1225 470]);
add_block('simulink/Discrete/Unit Delay', [mdl '/Delay_w'], ...
    'SampleTime', num2str(p.Ts), 'InitialCondition', '0', 'Position', [1190 560 1225 590]);

add_block('simulink/Signal Routing/Mux', [mdl '/Mux_Angles'], 'Inputs', '4', 'Position', [1270 60 1275 160]);
add_block('simulink/Signal Routing/Mux', [mdl '/Mux_Speeds'], 'Inputs', '5', 'Position', [1270 220 1275 330]);
add_block('simulink/Signal Routing/Mux', [mdl '/Mux_Iabc'],   'Inputs', '5', 'Position', [1270 390 1275 500]);
add_block('simulink/Signal Routing/Mux', [mdl '/Mux_Diag'],   'Inputs', '3', 'Position', [1270 550 1275 650]);

add_block('simulink/Sinks/Scope', [mdl '/Scope_Angles'],   'Position', [1320 60 1370 160]);
add_block('simulink/Sinks/Scope', [mdl '/Scope_Speeds'],   'Position', [1320 225 1370 325]);
add_block('simulink/Sinks/Scope', [mdl '/Scope_Currents'], 'Position', [1320 390 1370 490]);

add_block('simulink/Sinks/To Workspace', [mdl '/TW_Angles'], 'VariableName', 'log_angles', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Position', [1410 60 1490 160]);
add_block('simulink/Sinks/To Workspace', [mdl '/TW_Speeds'], 'VariableName', 'log_speeds', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Position', [1410 225 1490 325]);
add_block('simulink/Sinks/To Workspace', [mdl '/TW_Iabc'], 'VariableName', 'log_iabc', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Position', [1410 390 1490 490]);
add_block('simulink/Sinks/To Workspace', [mdl '/TW_Diag'], 'VariableName', 'log_diag', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Position', [1410 550 1490 650]);

add_block('simulink/Sinks/Terminator', [mdl '/Term_iqref'], 'Position', [1210 700 1240 720]);

% ---------------- wiring ----------------
L = { ...
 'Clock/1','Ref_Profile/1'; ...
 'Clock/1','HFI_Observer/5'; ...
 'CFG/1','FOC_Controller/7'; ...
 'CFG/1','HFI_Observer/6'; ...
 'CFG/1','PMSM_Plant/4'; ...
 'CFG/1','SMO_PLL/5'; ...
 'CFG/1','Observer_Fusion/6'; ...
 'Ref_Profile/1','FOC_Controller/1'; ...
 'Ref_Profile/1','Mux_Speeds/1'; ...
 'Ref_Profile/2','PMSM_Plant/3'; ...
 'Observer_Fusion/1','Delay_theta/1'; ...
 'Observer_Fusion/2','Delay_w/1'; ...
 'Delay_theta/1','FOC_Controller/6'; ...
 'Delay_w/1','FOC_Controller/2'; ...
 'Delay_theta/1','Mux_Angles/4'; ...
 'Delay_w/1','Mux_Speeds/5'; ...
 'Observer_Fusion/3','Mux_Diag/3'; ...
 'FOC_Controller/1','HFI_Observer/1'; ...
 'FOC_Controller/2','HFI_Observer/2'; ...
 'FOC_Controller/5','Term_iqref/1'; ...
 'FOC_Controller/3','Mux_Iabc/4'; ...
 'FOC_Controller/4','Mux_Iabc/5'; ...
 'HFI_Observer/1','Delay_ua/1'; ...
 'HFI_Observer/2','Delay_ub/1'; ...
 'HFI_Observer/3','Mux_Angles/3'; ...
 'HFI_Observer/3','Observer_Fusion/4'; ...
 'HFI_Observer/4','Observer_Fusion/5'; ...
 'HFI_Observer/4','Mux_Speeds/4'; ...
 'HFI_Observer/5','Mux_Diag/2'; ...
 'Delay_ua/1','PMSM_Plant/1'; ...
 'Delay_ub/1','PMSM_Plant/2'; ...
 'Delay_ua/1','SMO_PLL/1'; ...
 'Delay_ub/1','SMO_PLL/2'; ...
 'PMSM_Plant/1','FOC_Controller/3'; ...
 'PMSM_Plant/2','FOC_Controller/4'; ...
 'PMSM_Plant/3','FOC_Controller/5'; ...
 'PMSM_Plant/4','SMO_PLL/3'; ...
 'PMSM_Plant/5','SMO_PLL/4'; ...
 'PMSM_Plant/4','HFI_Observer/3'; ...
 'PMSM_Plant/5','HFI_Observer/4'; ...
 'PMSM_Plant/1','Mux_Iabc/1'; ...
 'PMSM_Plant/2','Mux_Iabc/2'; ...
 'PMSM_Plant/3','Mux_Iabc/3'; ...
 'PMSM_Plant/6','Mux_Angles/1'; ...
 'PMSM_Plant/7','Mux_Speeds/2'; ...
 'SMO_PLL/1','Mux_Angles/2'; ...
 'SMO_PLL/1','Observer_Fusion/1'; ...
 'SMO_PLL/2','Observer_Fusion/2'; ...
 'SMO_PLL/2','Mux_Speeds/3'; ...
 'SMO_PLL/3','Observer_Fusion/3'; ...
 'SMO_PLL/3','Mux_Diag/1'; ...
 'Mux_Angles/1','Scope_Angles/1'; ...
 'Mux_Angles/1','TW_Angles/1'; ...
 'Mux_Speeds/1','Scope_Speeds/1'; ...
 'Mux_Speeds/1','TW_Speeds/1'; ...
 'Mux_Iabc/1','Scope_Currents/1'; ...
 'Mux_Iabc/1','TW_Iabc/1'; ...
 'Mux_Diag/1','TW_Diag/1'};

for k = 1:size(L,1)
    add_line(mdl, L{k,1}, L{k,2}, 'autorouting', 'on');
end

set_param(mdl, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(p.Ts), 'StopTime', num2str(p.Tstop), ...
    'SaveOutput', 'off', 'SaveTime', 'off', 'SaveState', 'off', ...
    'AlgebraicLoopMsg', 'error');

save_system(mdl);
fprintf('SH: model %s.slx written to %s\n', mdl, here);

names = {'Ref_Profile','FOC_Controller','HFI_Observer','PMSM_Plant','SMO_PLL','Observer_Fusion'};
for k = 1:numel(names)
    pr = get_param([mdl '/' names{k}], 'Ports');
    fprintf('SH: ports %-16s in=%d out=%d\n', names{k}, pr(1), pr(2));
end
end

function add_chart(mdl, name, mfile, position)
blk = [mdl '/' name];
add_block('simulink/User-Defined Functions/MATLAB Function', blk, 'Position', position);
rt  = sfroot;
ch  = rt.find('-isa', 'Stateflow.EMChart', 'Path', blk);
if numel(ch) ~= 1
    error('build:chartNotFound', 'expected 1 EMChart for %s, found %d', blk, numel(ch));
end
ch(1).Script = fileread(mfile);
end
